version: '3.3'

services:

  service-registry:
    container_name: service-registry
    image: andrewperez/service-registry:2.0
    ports:
      - "8099:8099"
    expose:
      - 8099
    networks:
      - app_web

  service-product:
    container_name: service-product
    image: andrewperez/service-product:2.3
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL = jdbc:postgresql://java_db:5432/arqui_soft
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = admin1234
    depends_on:
      - java_db

      - service-registry
    networks:
      - app_web

  service-user:
    container_name: service-user
    image: andrewperez/service-user:1.6
    ports:
      - "8080:8080"
      - "587:587"
    environment:
      - DATABASE_URL = jdbc:postgresql://java_db:5432/arqui_soft
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = admin1234
    depends_on:
      - java_db
      - service-registry
    networks:
      - app_web

  service-cart:
    container_name: service-cart
    image: andrewperez/service-cart:1.0
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL = jdbc:postgresql://java_db:5432/arqui_soft
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = admin1234
    depends_on:
      - java_db
      - service-registry
      - service-product
      - service-user
    networks:
      - app_web

  service-order:
    container_name: service-order
    image: andrewperez/service-order:1.3
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL = jdbc:postgresql://java_db:5432/arqui_soft
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = admin1234
    depends_on:
      - java_db
      - service-registry
      - service-cart
    networks:
      - app_web

  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: arqui_soft
    networks:
      - app_web


networks:
  app_web:
